In [1]:
# section2 


some_string = "   computer "

# 양옆 공백제거 

print(some_string.strip())

computer


In [3]:

# 타입 변환 

string = "720"

num = 720

print(type(int(string)))

print(type(str(num)))



<class 'int'>
<class 'str'>


In [5]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [27]:
import numpy as np

arr = np.array([1,2,3])

arr2 = np.array([2,5,6])

print(arr+arr2)

arr3 = np.arange(12).reshape(4,3)

print(arr3)

print(np.zeros([3,4])) # 2차원 형태의 zero 배열 생성

# 행렬곱 

print(arr@arr2) 

[3 7 9]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
30


## 리스트

### 리스트 선언 방법 

- 리스트 변수 = [ ]
- 리스트 변수 = list()
- 리스트 변수 = [ 데이터1, 데이터2 ]

# 리스트 추가 

- 리스트변수.append(데이터)
- 리스트변수.insert(인덱스 번호, 데이터)

### 리스트 삭제 

- 리스트 변수.remove(데이터)
- del 리스트변수[인덱스 번호]

### 리스트 데이터 수정 

- 리스트 변수[인덱스 번호] = 수정할 데이터


In [26]:
# 리스트 역순 정렬 

numbers = [2,1,4,3]

numbers.reverse() # 본래의 함수값을 바꾼다. 

print(numbers)

# 변수 정렬 

numbers.sort() # 본래의 함수 값을 바꾸기 때문에, 따로 변수에 대입해줄 필요가 없다 

print(numbers)

[3, 4, 1, 2]
[1, 2, 3, 4]


In [21]:
# 스플릿 함수 

str = "python, is easy"

print(str.split(",")) # ,를 기준으로 문자열을 나누겠다라는 의미 

['python', ' is easy']


## IF statement

if - elif - else

- if condition 1 and condition 2 :
- if condition 1 or condition 2 :
- if not condtion




In [30]:
string1 = '00000\t12345'

# \t -> tab 

print(string1)

00000	12345


In [39]:
# 사용자에게 데이터를 입력받았을 때 큰 숫자를 출력 

"""
1. if 문 
2. 리스트로 만든다. 
"""
import numpy as np

list_d = []
input_data1 = int(input("숫자를 입력하세요. : "))
input_data2 = int(input("숫자를 입력하세요. : "))
list_d.extend([input_data1,input_data2]) # append values ! 

# arr_numpy = np.array([])



empty_arr = np.empty_like(list_d)
empty_arr =  np.append(input_data1,input_data2)

print(f"max number {max(list_d)}")
print(f"sum number {sum(list_d)}")

print(f"max number {max(empty_arr)}")


숫자를 입력하세요. :  20
숫자를 입력하세요. :  30


max number 30
sum number 50
max number 30


### Exercise 19. 데이터 구조 (리스트)
* 사용자로부터 주민등록번호를 입력받아 뒷자리 맨 앞의 숫자를 출력하세요.
  - 주민등록번호 뒷자리 맨 앞자리는 성별을 나타냄
  - 예) 800001-1231231 주민번호를 입력받으면 1을 출력하면 됨
  - 1은 남성을 의미, 2는 여성을 의미, 최근 아이들은 3과 4를 사용함 

In [46]:


num = input("주민 번호를 입력하세요.").split("-") # transform list 

# num = input("주민 번호를 입력하세요.").split("-")[1][0] # transform list 

if num[1][0] == "1":
          print(num[1][0])
          print("남자입니다.")
    
else :
    print("여자입니다.")

주민 번호를 입력하세요. 800001-1231231


1
남자입니다.


In [47]:
# delete  " . "  

mystr = "a man goes into the room..."

print(mystr.strip("."))

a man goes into the room


### Exercise 22. 문자열 다루기 (strip)
* 주식 종목을 나타내는 종목코드에 공백과 줄바꿈 기호가 포함되어 있다. 공백과 줄바꿈 기호를 제거하고 종목코드만을 추출하라.
```python
code = '         000660\n            '
```
출력: '000660'

In [63]:
code = '         000660\n #  '  

print(code.strip(' \n #')) # 공백과 # 문자 제거 

000660


### Exercise 23. 문자열 다루기 (count)
* 다음 문자열에서 'Python' 문자열의 빈도수를 출력하라.
```python
python_desc = "Python is an interpreted high-level programming language for general-purpose programming. Created by Guido van Rossum and first released in 1991, Python has a design philosophy that emphasizes code readability, notably using significant whitespace."
```
출력 예: 2

In [66]:

# Python의 문자열의 빈도를 출력 

python_desc = "Python is an interpreted high-level programming language for general-purpose programming. Created by Guido van Rossum and first released in 1991, Python has a design philosophy that emphasizes code readability, notably using significant whitespace."

print(python_desc.count("Python")) # 대소문자를 구분한다. 



2


In [69]:
# 문자열 찾기 

python_desc = "Python is an interpreted high-level programming language for general-purpose programming. Created by Guido van Rossum and first released in 1991, Python has a design philosophy that emphasizes code readability, notably using significant whitespace."

print(python_desc.find("Python"))

# "If 'Python' is in python_desc, it should print 0, but if not, it should print 1."


# 예제 문자열
text = "Hello, world!"

# 'world'라는 서브스트링을 찾기
index = text.find("world")
print(index)  # 출력: 7 ('world'의 'w'가 문자열의 7번째 인덱스에 위치)

# 존재하지 않는 서브스트링을 찾기
index = text.find("Python")
print(index)  # 출력: -1 ('Python'은 문자열에 존재하지 않음)

# 'o'를 찾기
index = text.find("o")
print(index)  # 출력: 4 ('o'가 처음 나타나는 위치)

# 특정 위치 이후에서 찾기
index = text.find("o", 5)
print(index)  # 출력: 8 ('o'가 5번째 인덱스 이후에 나타나는 위치)

# 특정 범위 내에서 찾기
index = text.find("o", 5, 7)
print(index)  # 출력: -1 (5번째부터 7번째 인덱스 사이에 'o'가 없음)


0


In [3]:
# split 

list_data = '[Dave],[Kevin]'

print ( [ x[1:-1] for x in list_data.split(',')] )

['Dave', 'Kevin']


In [5]:
# password 

while 1:
    n = int(input('pw : '))
    if n == 1234:
        print("okay") 
        break 
    print("not same")

pw :  123


not same


pw :  22


not same


pw :  22


not same


pw :  33


not same


pw :  44


not same


pw :  55


not same


pw :  1234


okay


In [8]:
# find method 

string = input("id : ")

if string.find('park') == 0:
    print("park is god")
else:
    print("guess him")

id :  park


park is god


In [24]:
# 확장자 제거 

list_a = ['excel.txt', 'excel2.csv', 'excel3.csv']

# [print(x.split('.')[0]) for x in list_a]

# print( [ x for x in list_a if x.split('.')[1] == 'csv'])

for x in ( x  for x in list_a if x.split('.')[1] == 'csv') : # 제네레이터 표현식은 리턴값이 없으므로 

    print(x)


excel2.csv
excel3.csv
