In [1]:
# section2


some_string = "   computer "

# 両サイドの空白を除去

print(some_string.strip())

computer


In [3]:
# タイプ変換

string = "720"

num = 720

print(type(int(string)))

print(type(str(num)))

<class 'int'>
<class 'str'>


In [5]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [27]:
import numpy as np

arr = np.array([1,2,3])

arr2 = np.array([2,5,6])

print(arr+arr2)

arr3 = np.arange(12).reshape(4,3)

print(arr3)

print(np.zeros([3, 4]))  # 2次元形態のゼロ配列生成

# 行列積

print(arr@arr2) 

[3 7 9]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
30


## リスト

### リスト宣言方法

- リスト 変数 = [ ]
- リスト 変数 = list()
- リスト変数 = [データ1、データ2 ]

# リスト追加

- リスト変数.append(データ)
- リスト変数。insert（インデックス番号、データ）

### リスト削除

- リスト変数.remove(データ)
- del リスト変数[インデックス番号]

### リストデータ修正

- リスト変数[インデックス番号]=修正するデータ

In [26]:
# リスト逆順整列

numbers = [2,1,4,3]

numbers.reverse()  # 本来の関数値を変える。

print(numbers)

# 変数整列

numbers.sort()  # 元の関数値を変えるので、別に変数に代入する必要がない

print(numbers)

[3, 4, 1, 2]
[1, 2, 3, 4]


In [21]:
# スプリット関数

str = "python, is easy"

print(str.split(","))  # ,を基準に文字列を分けるという意味

['python', ' is easy']


## IF statement

if - elif - else

- if condition 1 and condition 2 :
- if condition 1 or condition 2 :
- if not condtion




In [30]:
string1 = '00000\t12345'

# \t -> tab 

print(string1)

00000	12345


In [39]:
# ユーザーからデータを入力されたときに大きな数字を出力

"""
1. if 문 
2. 리스트로 만든다. 
"""
import numpy as np

list_d = []
input_data1 = int(input("숫자를 입력하세요. : "))
input_data2 = int(input("숫자를 입력하세요. : "))
list_d.extend([input_data1,input_data2]) # append values ! 

# arr_numpy = np.array([])


empty_arr = np.empty_like(list_d)
empty_arr =  np.append(input_data1,input_data2)

print(f"max number {max(list_d)}")
print(f"sum number {sum(list_d)}")

print(f"max number {max(empty_arr)}")

숫자를 입력하세요. :  20
숫자를 입력하세요. :  30


max number 30
sum number 50
max number 30


### Exercise 19. データ構造(リスト)
* ユーザーから住民登録番号を入力してもらい、後ろの数字の一番前の数字を出力してください。
- 住民登録番号の後ろの数字の一番前の数字は性別を示す
- 例)8001-1231231 住民番号を入力されたら1を出力すれば良い
- 1は男性を意味、2は女性を意味、最近の子供たちは3と4を使う

In [46]:


num = input("주민 번호를 입력하세요.").split("-") # transform list 

# num = input("주민 번호를 입력하세요.").split("-")[1][0] # transform list 

if num[1][0] == "1":
          print(num[1][0])
          print("남자입니다.")
    
else :
    print("여자입니다.")

주민 번호를 입력하세요. 800001-1231231


1
남자입니다.


In [47]:
# delete  " . "  

mystr = "a man goes into the room..."

print(mystr.strip("."))

a man goes into the room


### Exercise 22.文字列扱い(strip)
* 株式銘柄を表す銘柄コードに空白と改行記号が含まれている。 空白と改行記号を除去し、種目コードだけを抽出せよ。
```python
code = ' 000660\n '
```
出力: '000660'

In [63]:
code = '         000660\n #  '  

print(code.strip(" \n #"))  # 空白と#文字除去

000660


### Exercise 23.文字列の扱い (count)
* 次の文字列で「Python」文字列の頻度数を出力せよ。
```python
python_desc = "Python is an interpreted high-level programming language for general-purpose programming. Created by Guido van Rossum and first released in 1991, Python has a design philosophy that emphasizes code readability, notably using significant whitespace."
```
出力 例 : 2

In [66]:
# Pythonの文字列の頻度を出力

python_desc = "Python is an interpreted high-level programming language for general-purpose programming. Created by Guido van Rossum and first released in 1991, Python has a design philosophy that emphasizes code readability, notably using significant whitespace."

print(python_desc.count("Python"))  # 大文字と小文字を区別する。

2


In [69]:
# 文字列検索

python_desc = "Python is an interpreted high-level programming language for general-purpose programming. Created by Guido van Rossum and first released in 1991, Python has a design philosophy that emphasizes code readability, notably using significant whitespace."

print(python_desc.find("Python"))

# "If 'Python' is in python_desc, it should print 0, but if not, it should print 1."

0
